FROM wire_app_image:1.1

RUN git clone https://github.com/wireapp/wire-desktop.git

RUN rm -rf wire-desktop

RUN git clone https://github.com/wireapp/wire-desktop.git

RUN rm -rf wire-desktop 

RUN git clone https://github.com/wireapp/wire-desktop.git

RUN rm -rf wire-desktop

RUN git clone https://github.com/wireapp/wire-desktop.git

RUN rm -rf wire-desktop

RUN git clone https://github.com/wireapp/wire-desktop.git

RUN rm -rf wire-desktop

RUN git clone https://github.com/wireapp/wire-desktop.git

RUN rm -rf wire-desktop

RUN git clone https://github.com/wireapp/wire-desktop.git

RUN rm -rf wire-desktop

